name: MGSnake
main: com.comze_instancelabs.mgsnake.Main
version: 1.2.0
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   sc:
      description: Main command
      usage: /sc [action]
      aliases: [snake, mgsnake]
