name: MGSnake
main: com.comze_instancelabs.mgsnake.Main
version: ${version}
author: [TheMrQuake,InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   sc:
      description: Main command
      usage: /sc [action]
      aliases: [snake, mgsnake]
